### ISSUE TITLE
Add Seasons_Stats.csv

### ISSUE THREAD

**Issue by pomber** [tttgm/playofflebron#1]
Hi! is Seasons_Stats.csv available anywhere?

**Comment by tttgm** [comment]
I just added it to the datasets/ folder!

**Comment by pomber** [comment]
Thanks!
I wanted to add Manu Ginobili to the plots.
Also, I tried ratios instead of differences:
![image](https://user-images.githubusercontent.com/1911623/40279238-4cbb6424-5c15-11e8-9be5-686810d823ad.png)
